// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sniffed_info.proto

#include "sniffed_info.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
constexpr FlowInfo::FlowInfo(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : s_addr_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , s_port_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , d_addr_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , d_port_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , rst_(0)
  , num_bytes_30_(0){}
struct FlowInfoDefaultTypeInternal {
  constexpr FlowInfoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~FlowInfoDefaultTypeInternal() {}
  union {
    FlowInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT FlowInfoDefaultTypeInternal _FlowInfo_default_instance_;
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_sniffed_5finfo_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_sniffed_5finfo_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_sniffed_5finfo_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_sniffed_5finfo_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::FlowInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::FlowInfo, s_addr_),
  PROTOBUF_FIELD_OFFSET(::FlowInfo, s_port_),
  PROTOBUF_FIELD_OFFSET(::FlowInfo, d_addr_),
  PROTOBUF_FIELD_OFFSET(::FlowInfo, d_port_),
  PROTOBUF_FIELD_OFFSET(::FlowInfo, num_bytes_30_),
  PROTOBUF_FIELD_OFFSET(::FlowInfo, rst_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::FlowInfo)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_FlowInfo_default_instance_),
};

const char descriptor_table_protodef_sniffed_5finfo_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022sniffed_info.proto\"m\n\010FlowInfo\022\016\n\006s_ad"
  "dr\030\001 \001(\t\022\016\n\006s_port\030\002 \001(\t\022\016\n\006d_addr\030\003 \001(\t"
  "\022\016\n\006d_port\030\004 \001(\t\022\024\n\014num_bytes_30\030\005 \001(\005\022\013"
  "\n\003rst\030\006 \001(\001b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_sniffed_5finfo_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sniffed_5finfo_2eproto = {
  false, false, 139, descriptor_table_protodef_sniffed_5finfo_2eproto, "sniffed_info.proto", 
  &descriptor_table_sniffed_5finfo_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_sniffed_5finfo_2eproto::offsets,
  file_level_metadata_sniffed_5finfo_2eproto, file_level_enum_descriptors_sniffed_5finfo_2eproto, file_level_service_descriptors_sniffed_5finfo_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_sniffed_5finfo_2eproto_getter() {
  return &descriptor_table_sniffed_5finfo_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_sniffed_5finfo_2eproto(&descriptor_table_sniffed_5finfo_2eproto);

// ===================================================================

class FlowInfo::_Internal {
 public:
};

FlowInfo::FlowInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:FlowInfo)
}
FlowInfo::FlowInfo(const FlowInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  s_addr_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_s_addr().empty()) {
    s_addr_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_s_addr(), 
      GetArenaForAllocation());
  }
  s_port_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_s_port().empty()) {
    s_port_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_s_port(), 
      GetArenaForAllocation());
  }
  d_addr_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_d_addr().empty()) {
    d_addr_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_d_addr(), 
      GetArenaForAllocation());
  }
  d_port_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_d_port().empty()) {
    d_port_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_d_port(), 
      GetArenaForAllocation());
  }
  ::memcpy(&rst_, &from.rst_,
    static_cast<size_t>(reinterpret_cast<char*>(&num_bytes_30_) -
    reinterpret_cast<char*>(&rst_)) + sizeof(num_bytes_30_));
  // @@protoc_insertion_point(copy_constructor:FlowInfo)
}

void FlowInfo::SharedCtor() {
s_addr_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
s_port_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
d_addr_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
d_port_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&rst_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&num_bytes_30_) -
    reinterpret_cast<char*>(&rst_)) + sizeof(num_bytes_30_));
}

FlowInfo::~FlowInfo() {
  // @@protoc_insertion_point(destructor:FlowInfo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void FlowInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  s_addr_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  s_port_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  d_addr_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  d_port_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void FlowInfo::ArenaDtor(void* object) {
  FlowInfo* _this = reinterpret_cast< FlowInfo* >(object);
  (void)_this;
}
void FlowInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void FlowInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void FlowInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:FlowInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  s_addr_.ClearToEmpty();
  s_port_.ClearToEmpty();
  d_addr_.ClearToEmpty();
  d_port_.ClearToEmpty();
  ::memset(&rst_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&num_bytes_30_) -
      reinterpret_cast<char*>(&rst_)) + sizeof(num_bytes_30_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FlowInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string s_addr = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_s_addr();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "FlowInfo.s_addr"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string s_port = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_s_port();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "FlowInfo.s_port"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string d_addr = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_d_addr();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "FlowInfo.d_addr"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string d_port = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_d_port();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "FlowInfo.d_port"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 num_bytes_30 = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          num_bytes_30_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double rst = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 49)) {
          rst_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* FlowInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:FlowInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string s_addr = 1;
  if (!this->s_addr().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_s_addr().data(), static_cast<int>(this->_internal_s_addr().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "FlowInfo.s_addr");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_s_addr(), target);
  }

  // string s_port = 2;
  if (!this->s_port().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_s_port().data(), static_cast<int>(this->_internal_s_port().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "FlowInfo.s_port");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_s_port(), target);
  }

  // string d_addr = 3;
  if (!this->d_addr().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_d_addr().data(), static_cast<int>(this->_internal_d_addr().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "FlowInfo.d_addr");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_d_addr(), target);
  }

  // string d_port = 4;
  if (!this->d_port().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_d_port().data(), static_cast<int>(this->_internal_d_port().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "FlowInfo.d_port");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_d_port(), target);
  }

  // int32 num_bytes_30 = 5;
  if (this->num_bytes_30() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(5, this->_internal_num_bytes_30(), target);
  }

  // double rst = 6;
  if (!(this->rst() <= 0 && this->rst() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(6, this->_internal_rst(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FlowInfo)
  return target;
}

size_t FlowInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:FlowInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string s_addr = 1;
  if (!this->s_addr().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_s_addr());
  }

  // string s_port = 2;
  if (!this->s_port().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_s_port());
  }

  // string d_addr = 3;
  if (!this->d_addr().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_d_addr());
  }

  // string d_port = 4;
  if (!this->d_port().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_d_port());
  }

  // double rst = 6;
  if (!(this->rst() <= 0 && this->rst() >= 0)) {
    total_size += 1 + 8;
  }

  // int32 num_bytes_30 = 5;
  if (this->num_bytes_30() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_num_bytes_30());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FlowInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:FlowInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const FlowInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<FlowInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:FlowInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:FlowInfo)
    MergeFrom(*source);
  }
}

void FlowInfo::MergeFrom(const FlowInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:FlowInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from.s_addr().empty()) {
    _internal_set_s_addr(from._internal_s_addr());
  }
  if (!from.s_port().empty()) {
    _internal_set_s_port(from._internal_s_port());
  }
  if (!from.d_addr().empty()) {
    _internal_set_d_addr(from._internal_d_addr());
  }
  if (!from.d_port().empty()) {
    _internal_set_d_port(from._internal_d_port());
  }
  if (!(from.rst() <= 0 && from.rst() >= 0)) {
    _internal_set_rst(from._internal_rst());
  }
  if (from.num_bytes_30() != 0) {
    _internal_set_num_bytes_30(from._internal_num_bytes_30());
  }
}

void FlowInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:FlowInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FlowInfo::CopyFrom(const FlowInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FlowInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FlowInfo::IsInitialized() const {
  return true;
}

void FlowInfo::InternalSwap(FlowInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &s_addr_, GetArenaForAllocation(),
      &other->s_addr_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &s_port_, GetArenaForAllocation(),
      &other->s_port_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &d_addr_, GetArenaForAllocation(),
      &other->d_addr_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &d_port_, GetArenaForAllocation(),
      &other->d_port_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FlowInfo, num_bytes_30_)
      + sizeof(FlowInfo::num_bytes_30_)
      - PROTOBUF_FIELD_OFFSET(FlowInfo, rst_)>(
          reinterpret_cast<char*>(&rst_),
          reinterpret_cast<char*>(&other->rst_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FlowInfo::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_sniffed_5finfo_2eproto_getter, &descriptor_table_sniffed_5finfo_2eproto_once,
      file_level_metadata_sniffed_5finfo_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::FlowInfo* Arena::CreateMaybeMessage< ::FlowInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::FlowInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
