// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sniffed_info.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sniffed_5finfo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_sniffed_5finfo_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sniffed_5finfo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_sniffed_5finfo_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sniffed_5finfo_2eproto;
class FlowInfo;
struct FlowInfoDefaultTypeInternal;
extern FlowInfoDefaultTypeInternal _FlowInfo_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::FlowInfo* Arena::CreateMaybeMessage<::FlowInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class FlowInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:FlowInfo) */ {
 public:
  inline FlowInfo() : FlowInfo(nullptr) {}
  ~FlowInfo() override;
  explicit constexpr FlowInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FlowInfo(const FlowInfo& from);
  FlowInfo(FlowInfo&& from) noexcept
    : FlowInfo() {
    *this = ::std::move(from);
  }

  inline FlowInfo& operator=(const FlowInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline FlowInfo& operator=(FlowInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FlowInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const FlowInfo* internal_default_instance() {
    return reinterpret_cast<const FlowInfo*>(
               &_FlowInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FlowInfo& a, FlowInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(FlowInfo* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FlowInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FlowInfo* New() const final {
    return new FlowInfo();
  }

  FlowInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FlowInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FlowInfo& from);
  void MergeFrom(const FlowInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FlowInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "FlowInfo";
  }
  protected:
  explicit FlowInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSAddrFieldNumber = 1,
    kSPortFieldNumber = 2,
    kDAddrFieldNumber = 3,
    kDPortFieldNumber = 4,
    kRstFieldNumber = 6,
    kNumBytes30FieldNumber = 5,
  };
  // string s_addr = 1;
  void clear_s_addr();
  const std::string& s_addr() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_s_addr(ArgT0&& arg0, ArgT... args);
  std::string* mutable_s_addr();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_s_addr();
  void set_allocated_s_addr(std::string* s_addr);
  private:
  const std::string& _internal_s_addr() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_s_addr(const std::string& value);
  std::string* _internal_mutable_s_addr();
  public:

  // string s_port = 2;
  void clear_s_port();
  const std::string& s_port() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_s_port(ArgT0&& arg0, ArgT... args);
  std::string* mutable_s_port();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_s_port();
  void set_allocated_s_port(std::string* s_port);
  private:
  const std::string& _internal_s_port() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_s_port(const std::string& value);
  std::string* _internal_mutable_s_port();
  public:

  // string d_addr = 3;
  void clear_d_addr();
  const std::string& d_addr() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_d_addr(ArgT0&& arg0, ArgT... args);
  std::string* mutable_d_addr();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_d_addr();
  void set_allocated_d_addr(std::string* d_addr);
  private:
  const std::string& _internal_d_addr() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_d_addr(const std::string& value);
  std::string* _internal_mutable_d_addr();
  public:

  // string d_port = 4;
  void clear_d_port();
  const std::string& d_port() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_d_port(ArgT0&& arg0, ArgT... args);
  std::string* mutable_d_port();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_d_port();
  void set_allocated_d_port(std::string* d_port);
  private:
  const std::string& _internal_d_port() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_d_port(const std::string& value);
  std::string* _internal_mutable_d_port();
  public:

  // double rst = 6;
  void clear_rst();
  double rst() const;
  void set_rst(double value);
  private:
  double _internal_rst() const;
  void _internal_set_rst(double value);
  public:

  // int32 num_bytes_30 = 5;
  void clear_num_bytes_30();
  ::PROTOBUF_NAMESPACE_ID::int32 num_bytes_30() const;
  void set_num_bytes_30(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_num_bytes_30() const;
  void _internal_set_num_bytes_30(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:FlowInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr s_addr_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr s_port_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr d_addr_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr d_port_;
  double rst_;
  ::PROTOBUF_NAMESPACE_ID::int32 num_bytes_30_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sniffed_5finfo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FlowInfo

// string s_addr = 1;
inline void FlowInfo::clear_s_addr() {
  s_addr_.ClearToEmpty();
}
inline const std::string& FlowInfo::s_addr() const {
  // @@protoc_insertion_point(field_get:FlowInfo.s_addr)
  return _internal_s_addr();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FlowInfo::set_s_addr(ArgT0&& arg0, ArgT... args) {
 
 s_addr_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:FlowInfo.s_addr)
}
inline std::string* FlowInfo::mutable_s_addr() {
  // @@protoc_insertion_point(field_mutable:FlowInfo.s_addr)
  return _internal_mutable_s_addr();
}
inline const std::string& FlowInfo::_internal_s_addr() const {
  return s_addr_.Get();
}
inline void FlowInfo::_internal_set_s_addr(const std::string& value) {
  
  s_addr_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* FlowInfo::_internal_mutable_s_addr() {
  
  return s_addr_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* FlowInfo::release_s_addr() {
  // @@protoc_insertion_point(field_release:FlowInfo.s_addr)
  return s_addr_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void FlowInfo::set_allocated_s_addr(std::string* s_addr) {
  if (s_addr != nullptr) {
    
  } else {
    
  }
  s_addr_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), s_addr,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:FlowInfo.s_addr)
}

// string s_port = 2;
inline void FlowInfo::clear_s_port() {
  s_port_.ClearToEmpty();
}
inline const std::string& FlowInfo::s_port() const {
  // @@protoc_insertion_point(field_get:FlowInfo.s_port)
  return _internal_s_port();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FlowInfo::set_s_port(ArgT0&& arg0, ArgT... args) {
 
 s_port_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:FlowInfo.s_port)
}
inline std::string* FlowInfo::mutable_s_port() {
  // @@protoc_insertion_point(field_mutable:FlowInfo.s_port)
  return _internal_mutable_s_port();
}
inline const std::string& FlowInfo::_internal_s_port() const {
  return s_port_.Get();
}
inline void FlowInfo::_internal_set_s_port(const std::string& value) {
  
  s_port_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* FlowInfo::_internal_mutable_s_port() {
  
  return s_port_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* FlowInfo::release_s_port() {
  // @@protoc_insertion_point(field_release:FlowInfo.s_port)
  return s_port_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void FlowInfo::set_allocated_s_port(std::string* s_port) {
  if (s_port != nullptr) {
    
  } else {
    
  }
  s_port_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), s_port,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:FlowInfo.s_port)
}

// string d_addr = 3;
inline void FlowInfo::clear_d_addr() {
  d_addr_.ClearToEmpty();
}
inline const std::string& FlowInfo::d_addr() const {
  // @@protoc_insertion_point(field_get:FlowInfo.d_addr)
  return _internal_d_addr();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FlowInfo::set_d_addr(ArgT0&& arg0, ArgT... args) {
 
 d_addr_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:FlowInfo.d_addr)
}
inline std::string* FlowInfo::mutable_d_addr() {
  // @@protoc_insertion_point(field_mutable:FlowInfo.d_addr)
  return _internal_mutable_d_addr();
}
inline const std::string& FlowInfo::_internal_d_addr() const {
  return d_addr_.Get();
}
inline void FlowInfo::_internal_set_d_addr(const std::string& value) {
  
  d_addr_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* FlowInfo::_internal_mutable_d_addr() {
  
  return d_addr_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* FlowInfo::release_d_addr() {
  // @@protoc_insertion_point(field_release:FlowInfo.d_addr)
  return d_addr_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void FlowInfo::set_allocated_d_addr(std::string* d_addr) {
  if (d_addr != nullptr) {
    
  } else {
    
  }
  d_addr_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), d_addr,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:FlowInfo.d_addr)
}

// string d_port = 4;
inline void FlowInfo::clear_d_port() {
  d_port_.ClearToEmpty();
}
inline const std::string& FlowInfo::d_port() const {
  // @@protoc_insertion_point(field_get:FlowInfo.d_port)
  return _internal_d_port();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FlowInfo::set_d_port(ArgT0&& arg0, ArgT... args) {
 
 d_port_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:FlowInfo.d_port)
}
inline std::string* FlowInfo::mutable_d_port() {
  // @@protoc_insertion_point(field_mutable:FlowInfo.d_port)
  return _internal_mutable_d_port();
}
inline const std::string& FlowInfo::_internal_d_port() const {
  return d_port_.Get();
}
inline void FlowInfo::_internal_set_d_port(const std::string& value) {
  
  d_port_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* FlowInfo::_internal_mutable_d_port() {
  
  return d_port_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* FlowInfo::release_d_port() {
  // @@protoc_insertion_point(field_release:FlowInfo.d_port)
  return d_port_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void FlowInfo::set_allocated_d_port(std::string* d_port) {
  if (d_port != nullptr) {
    
  } else {
    
  }
  d_port_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), d_port,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:FlowInfo.d_port)
}

// int32 num_bytes_30 = 5;
inline void FlowInfo::clear_num_bytes_30() {
  num_bytes_30_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FlowInfo::_internal_num_bytes_30() const {
  return num_bytes_30_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FlowInfo::num_bytes_30() const {
  // @@protoc_insertion_point(field_get:FlowInfo.num_bytes_30)
  return _internal_num_bytes_30();
}
inline void FlowInfo::_internal_set_num_bytes_30(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  num_bytes_30_ = value;
}
inline void FlowInfo::set_num_bytes_30(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_num_bytes_30(value);
  // @@protoc_insertion_point(field_set:FlowInfo.num_bytes_30)
}

// double rst = 6;
inline void FlowInfo::clear_rst() {
  rst_ = 0;
}
inline double FlowInfo::_internal_rst() const {
  return rst_;
}
inline double FlowInfo::rst() const {
  // @@protoc_insertion_point(field_get:FlowInfo.rst)
  return _internal_rst();
}
inline void FlowInfo::_internal_set_rst(double value) {
  
  rst_ = value;
}
inline void FlowInfo::set_rst(double value) {
  _internal_set_rst(value);
  // @@protoc_insertion_point(field_set:FlowInfo.rst)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_sniffed_5finfo_2eproto
