# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sniffed_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sniffed_info.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12sniffed_info.proto\"m\n\x08\x46lowInfo\x12\x0e\n\x06s_addr\x18\x01 \x01(\t\x12\x0e\n\x06s_port\x18\x02 \x01(\t\x12\x0e\n\x06\x64_addr\x18\x03 \x01(\t\x12\x0e\n\x06\x64_port\x18\x04 \x01(\t\x12\x14\n\x0cnum_bytes_30\x18\x05 \x01(\x05\x12\x0b\n\x03rst\x18\x06 \x01(\x01\x62\x06proto3'
)




_FLOWINFO = _descriptor.Descriptor(
  name='FlowInfo',
  full_name='FlowInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='s_addr', full_name='FlowInfo.s_addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='s_port', full_name='FlowInfo.s_port', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='d_addr', full_name='FlowInfo.d_addr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='d_port', full_name='FlowInfo.d_port', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_bytes_30', full_name='FlowInfo.num_bytes_30', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rst', full_name='FlowInfo.rst', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=131,
)

DESCRIPTOR.message_types_by_name['FlowInfo'] = _FLOWINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FlowInfo = _reflection.GeneratedProtocolMessageType('FlowInfo', (_message.Message,), {
  'DESCRIPTOR' : _FLOWINFO,
  '__module__' : 'sniffed_info_pb2'
  # @@protoc_insertion_point(class_scope:FlowInfo)
  })
_sym_db.RegisterMessage(FlowInfo)


# @@protoc_insertion_point(module_scope)
